---
name: Terraform

on:
  push:
    branches:
      - "main"
      - "docs/**"
      - "feature/**"
      - "fix/**"
      - "wip/**"
    paths-ignore:
      - "**/**.md"
  pull_request:
    branches:
      - "docs/**"
      - "feature/**"
      - "fix/**"
      - "wip/**"
    paths-ignore:
      - "**/**.md"

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Inject Terraform Documentation"
        uses: terraform-docs/gh-actions@v1
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.1
      - name: Terraform Format Check
        run: terraform fmt -check
        id: fmt
        continue-on-error: false
      - name: Terraform Format
        run: terraform fmt -recursive .
        continue-on-error: false
      - name: Terraform Initialize
        id: init
        run: |
          terraform init
        continue-on-error: false
      - name: Terraform Validate
        id: validate
        run: terraform validate
        continue-on-error: false
