---
name: Terraform

permissions: read-all

on:
  push:
    branches:
      - "main"
      - "docs/**"
      - "feature/**"
      - "fix/**"
      - "wip/**"
    paths-ignore:
      - "**/**.md"
  pull_request:
    branches:
      - "docs/**"
      - "feature/**"
      - "fix/**"
      - "wip/**"
    paths-ignore:
      - "**/**.md"

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: test
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    defaults:
      run:
        shell: bash
    env:
      TF_IN_AUTOMATION: "NON_EMPTY_VALUE" # https://developer.hashicorp.com/terraform/tutorials/automation/automate-terraform#controlling-terraform-output-in-automation
      ACTIONS_ALLOW_UNSECURE_COMMANDS: false
    permissions:
      actions: write
      checks: write
      contents: write
    steps:
      - uses: actions/checkout@v3
        continue-on-error: false
      - name: "Inject Terraform Documentation"
        uses: terraform-docs/gh-actions@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true # https://github.com/terraform-docs/gh-actions/issues/97#issuecomment-1335108516
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
        continue-on-error: false
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.1
        continue-on-error: false
      - name: Terraform Format Check
        run: |
          terraform fmt \
            -check
        id: fmt
        continue-on-error: false
      - name: Terraform Format
        run: |
          terraform fmt \
            -recursive .
        continue-on-error: false
      - name: Terraform Initialize
        id: init
        run: |
          terraform init \
            -input=false \
            -lock=true \
            -lock-timeout=0s
        continue-on-error: false
      - name: Terraform Validate
        id: validate
        run: |
          terraform validate
        continue-on-error: false
